version: '3.4'

services:
  mt.api:
    image: ${DOCKER_REGISTRY-}mtapi
    build:
      context: .
      dockerfile: mt.API/Dockerfile
    ports:
      - 5100:443
      - 5200:80

  mt.consumer:
    image: ${DOCKER_REGISTRY-}mtconsumer
    build:
      context: .
      dockerfile: mt.Consumer/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672