version: '3.4'

services:
  mt.api:
    image: ${DOCKER_REGISTRY-}mtapi
    build:
      context: .
      dockerfile: mt.API/Dockerfile
    depends_on:
       - rabbitmq

  mt.consumer:
    image: ${DOCKER_REGISTRY-}mtconsumer
    build:
      context: .
      dockerfile: mt.Consumer/Dockerfile
    depends_on:
       - rabbitmq

  mt2.consumer:
    image: ${DOCKER_REGISTRY-}mtconsumer2
    build:
      context: .
      dockerfile: mt.Consumer/Dockerfile
    depends_on:
       - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672