version: '3.4'

services:
  mt.api:
    image: ${DOCKER_REGISTRY-}mtapi
    build:
      context: .
      dockerfile: mt.API/Dockerfile

  mt.consumer:
    image: ${DOCKER_REGISTRY-}mtconsumer
    build:
      context: .
      dockerfile: mt.Consumer/Dockerfile

